### ISSUE TITLE
What is stored in unit_list?

### ISSUE THREAD

**Issue by thalesbsfr** [Fusion4233919/SAKT#1]
Hello Fusion4233919,

I'm trying to understand the SAKT architecture by your implementation, but I can't understand what is stored in unit_list_val and unit_list_train. Is the student's ID?

**Comment by Fusion4233919** [comment]
The unit_list is just a variable that assists in computing the performance of the model.

The sequence of student exercises is divided into segments of length window_size and then placed into the attention mechanism. However, not every segment is filled with data, and the parts without data are filled with zeros to keep the length consistent.

The number of non-zero data in this fragment is recorded in unit_list.
